// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/master.proto

package proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterWorkerRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Secret               string   `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterWorkerRequest) Reset()         { *m = RegisterWorkerRequest{} }
func (m *RegisterWorkerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterWorkerRequest) ProtoMessage()    {}
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31543f0e9829c49c, []int{0}
}

func (m *RegisterWorkerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterWorkerRequest.Unmarshal(m, b)
}
func (m *RegisterWorkerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterWorkerRequest.Marshal(b, m, deterministic)
}
func (m *RegisterWorkerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterWorkerRequest.Merge(m, src)
}
func (m *RegisterWorkerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterWorkerRequest.Size(m)
}
func (m *RegisterWorkerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterWorkerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterWorkerRequest proto.InternalMessageInfo

func (m *RegisterWorkerRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RegisterWorkerRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RegisterWorkerRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type RegisterWorkerResponse struct {
	WorkerId             int32    `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterWorkerResponse) Reset()         { *m = RegisterWorkerResponse{} }
func (m *RegisterWorkerResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterWorkerResponse) ProtoMessage()    {}
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31543f0e9829c49c, []int{1}
}

func (m *RegisterWorkerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterWorkerResponse.Unmarshal(m, b)
}
func (m *RegisterWorkerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterWorkerResponse.Marshal(b, m, deterministic)
}
func (m *RegisterWorkerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterWorkerResponse.Merge(m, src)
}
func (m *RegisterWorkerResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterWorkerResponse.Size(m)
}
func (m *RegisterWorkerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterWorkerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterWorkerResponse proto.InternalMessageInfo

func (m *RegisterWorkerResponse) GetWorkerId() int32 {
	if m != nil {
		return m.WorkerId
	}
	return 0
}

type FinishExtractingLinksRequest struct {
	WorkerId             int32    `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Links                []string `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinishExtractingLinksRequest) Reset()         { *m = FinishExtractingLinksRequest{} }
func (m *FinishExtractingLinksRequest) String() string { return proto.CompactTextString(m) }
func (*FinishExtractingLinksRequest) ProtoMessage()    {}
func (*FinishExtractingLinksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31543f0e9829c49c, []int{2}
}

func (m *FinishExtractingLinksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishExtractingLinksRequest.Unmarshal(m, b)
}
func (m *FinishExtractingLinksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishExtractingLinksRequest.Marshal(b, m, deterministic)
}
func (m *FinishExtractingLinksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishExtractingLinksRequest.Merge(m, src)
}
func (m *FinishExtractingLinksRequest) XXX_Size() int {
	return xxx_messageInfo_FinishExtractingLinksRequest.Size(m)
}
func (m *FinishExtractingLinksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishExtractingLinksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinishExtractingLinksRequest proto.InternalMessageInfo

func (m *FinishExtractingLinksRequest) GetWorkerId() int32 {
	if m != nil {
		return m.WorkerId
	}
	return 0
}

func (m *FinishExtractingLinksRequest) GetLinks() []string {
	if m != nil {
		return m.Links
	}
	return nil
}

type ExploreWebsiteRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExploreWebsiteRequest) Reset()         { *m = ExploreWebsiteRequest{} }
func (m *ExploreWebsiteRequest) String() string { return proto.CompactTextString(m) }
func (*ExploreWebsiteRequest) ProtoMessage()    {}
func (*ExploreWebsiteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31543f0e9829c49c, []int{3}
}

func (m *ExploreWebsiteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExploreWebsiteRequest.Unmarshal(m, b)
}
func (m *ExploreWebsiteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExploreWebsiteRequest.Marshal(b, m, deterministic)
}
func (m *ExploreWebsiteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExploreWebsiteRequest.Merge(m, src)
}
func (m *ExploreWebsiteRequest) XXX_Size() int {
	return xxx_messageInfo_ExploreWebsiteRequest.Size(m)
}
func (m *ExploreWebsiteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExploreWebsiteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExploreWebsiteRequest proto.InternalMessageInfo

func (m *ExploreWebsiteRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterWorkerRequest)(nil), "proto.RegisterWorkerRequest")
	proto.RegisterType((*RegisterWorkerResponse)(nil), "proto.RegisterWorkerResponse")
	proto.RegisterType((*FinishExtractingLinksRequest)(nil), "proto.FinishExtractingLinksRequest")
	proto.RegisterType((*ExploreWebsiteRequest)(nil), "proto.ExploreWebsiteRequest")
}

func init() { proto.RegisterFile("proto/master.proto", fileDescriptor_31543f0e9829c49c) }

var fileDescriptor_31543f0e9829c49c = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x9b, 0xf4, 0x4d, 0x79, 0x3b, 0x87, 0x22, 0x83, 0x2d, 0xa1, 0xad, 0x50, 0xd6, 0x4b,
	0xbd, 0xa4, 0xa0, 0xf8, 0x11, 0x2a, 0x0a, 0x8a, 0xb8, 0x82, 0x3d, 0x4a, 0xff, 0x8c, 0x71, 0x69,
	0x9a, 0x5d, 0x77, 0xb7, 0x58, 0x3f, 0xbb, 0x17, 0xc9, 0x6e, 0x22, 0x54, 0xd2, 0x9e, 0x76, 0x9e,
	0xd9, 0x99, 0x87, 0xf9, 0xcd, 0x00, 0x2a, 0x2d, 0xad, 0x9c, 0x6c, 0xe6, 0xc6, 0x92, 0x4e, 0x9c,
	0xc0, 0xc8, 0x3d, 0xfd, 0x41, 0x2a, 0x65, 0x9a, 0xd1, 0xc4, 0xa9, 0xc5, 0xf6, 0x6d, 0x42, 0x1b,
	0x65, 0xbf, 0x7c, 0x0d, 0x7b, 0x86, 0x2e, 0xa7, 0x54, 0x14, 0x5d, 0x33, 0xa9, 0xd7, 0xa4, 0x39,
	0x7d, 0x6c, 0xc9, 0x58, 0xec, 0x40, 0x28, 0x54, 0x1c, 0x8c, 0x82, 0x71, 0x9b, 0x87, 0x42, 0x21,
	0xc2, 0x3f, 0x25, 0xb5, 0x8d, 0xc3, 0x51, 0x30, 0x8e, 0xb8, 0x8b, 0xb1, 0x07, 0x2d, 0x43, 0x4b,
	0x4d, 0x36, 0x6e, 0xba, 0xba, 0x52, 0xb1, 0x6b, 0xe8, 0xfd, 0x35, 0x35, 0x4a, 0xe6, 0x86, 0x70,
	0x00, 0xed, 0x4f, 0x97, 0x79, 0x15, 0x2b, 0x67, 0x1e, 0xf1, 0xff, 0x3e, 0x71, 0xb7, 0x62, 0x4f,
	0x30, 0xbc, 0x11, 0xb9, 0x30, 0xef, 0xd3, 0x9d, 0xd5, 0xf3, 0xa5, 0x15, 0x79, 0x7a, 0x2f, 0xf2,
	0xb5, 0xa9, 0x46, 0x3a, 0xd6, 0x8c, 0xa7, 0x10, 0x65, 0x45, 0x71, 0x1c, 0x8e, 0x9a, 0xe3, 0x36,
	0xf7, 0x82, 0x5d, 0x40, 0x77, 0xba, 0x53, 0x99, 0xd4, 0x34, 0xa3, 0x85, 0x11, 0x96, 0x2a, 0xaf,
	0x13, 0x68, 0x6e, 0x75, 0x56, 0xf2, 0x15, 0xe1, 0xe5, 0x77, 0x00, 0xad, 0x07, 0xb7, 0x3e, 0x7c,
	0x84, 0xce, 0xfe, 0xfc, 0x38, 0xf4, 0xeb, 0x4a, 0x6a, 0x77, 0xd5, 0x3f, 0x3b, 0xf0, 0xeb, 0xa1,
	0x59, 0x03, 0x5f, 0xa0, 0x5b, 0x4b, 0x86, 0xe7, 0x65, 0xe7, 0x31, 0xee, 0x7e, 0x2f, 0xf1, 0x17,
	0x4c, 0xaa, 0x0b, 0x26, 0xd3, 0xe2, 0x82, 0xac, 0x81, 0xb7, 0xd0, 0xd9, 0xc7, 0xfb, 0x1d, 0xb4,
	0x96, 0xfa, 0xb0, 0xd3, 0xa2, 0xe5, 0x32, 0x57, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x36,
	0x4c, 0x44, 0x48, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterClient interface {
	RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error)
	FinishExtractingLinks(ctx context.Context, in *FinishExtractingLinksRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ExploreWebsite(ctx context.Context, in *ExploreWebsiteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type masterClient struct {
	cc *grpc.ClientConn
}

func NewMasterClient(cc *grpc.ClientConn) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error) {
	out := new(RegisterWorkerResponse)
	err := c.cc.Invoke(ctx, "/proto.Master/RegisterWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) FinishExtractingLinks(ctx context.Context, in *FinishExtractingLinksRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.Master/FinishExtractingLinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) ExploreWebsite(ctx context.Context, in *ExploreWebsiteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.Master/ExploreWebsite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
type MasterServer interface {
	RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error)
	FinishExtractingLinks(context.Context, *FinishExtractingLinksRequest) (*empty.Empty, error)
	ExploreWebsite(context.Context, *ExploreWebsiteRequest) (*empty.Empty, error)
}

// UnimplementedMasterServer can be embedded to have forward compatible implementations.
type UnimplementedMasterServer struct {
}

func (*UnimplementedMasterServer) RegisterWorker(ctx context.Context, req *RegisterWorkerRequest) (*RegisterWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (*UnimplementedMasterServer) FinishExtractingLinks(ctx context.Context, req *FinishExtractingLinksRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishExtractingLinks not implemented")
}
func (*UnimplementedMasterServer) ExploreWebsite(ctx context.Context, req *ExploreWebsiteRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExploreWebsite not implemented")
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Master/RegisterWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).RegisterWorker(ctx, req.(*RegisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_FinishExtractingLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishExtractingLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).FinishExtractingLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Master/FinishExtractingLinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).FinishExtractingLinks(ctx, req.(*FinishExtractingLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_ExploreWebsite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExploreWebsiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).ExploreWebsite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Master/ExploreWebsite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).ExploreWebsite(ctx, req.(*ExploreWebsiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _Master_RegisterWorker_Handler,
		},
		{
			MethodName: "FinishExtractingLinks",
			Handler:    _Master_FinishExtractingLinks_Handler,
		},
		{
			MethodName: "ExploreWebsite",
			Handler:    _Master_ExploreWebsite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/master.proto",
}
